import type {NextPage} from 'next'
import Head from 'next/head'
import {useEffect, useState} from "react";
import {getCatsByCategoryId, getCatsCategories, setCatAsFavourite} from "../../src/services/api.service";
import Image from 'next/image';
import {useRouter} from 'next/router'
import {InferGetStaticPropsType} from 'next';

const CategoryPage = ({cats} : {cats: any[]}) => {

    const router = useRouter();
    const {id} = router.query;

    return (
        <>
            <Head>
                <title>Next.js Demo | {id}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.png"/>
            </Head>

            <p className='main--p'>Cats with <strong>{id}</strong></p>
            {cats.map(cat => (
                <div className='main--box main--image'
                     onClick={() => setCatAsFavourite(cat.id)}
                     key={cat.id}>
                    <Image
                        alt={`cat pic id ${cat.id}`}
                        src={cat.url}
                        width={300}
                        height={300}
                        layout='responsive'
                    />
                    <button/>

                </div>
            ))}
        </>
    )
}

export async function getStaticProps({params} : {params: {id: string}}) {
    const {id} = params;
    const cats = await getCatsByCategoryId(id);
    return {
        props: {cats},
    }
}

export async function getStaticPaths() {

    const paths = await getCatsCategories();
    return {
        paths,
        fallback: true
    };
}


export default CategoryPage;
